#!/bin/bash

read -p "Ingrese su nombre: " name

declare -i password=0
read -p "Ingrese la contraseña: " password

if [[ "$name" == "pedro" || "$name" == "juan" ]]
then
	if(("$password" == "1234"))
	echo "Hola $name ! "
else 
	echo "Usuario invalido!"
fi

exit 0
